working_directory = "None"
[window]
opacity = 1
startup_mode = "Maximized"
[font]
normal = { family = "Lilex Nerd Font", style = "Regular" }
bold = { family = "Lilex Nerd Font", style = "Bold" }
italic = { family = "Lilex Nerd Font", style = "Italic" }
bold_italic = { family = "Lilex Nerd Font", style = "Bold Italic" }
size = 11