working_directory = "None"
[window]
opacity = 0.95
decorations = "full"
title = "Terminal - Alacritty"
[window.padding]
x = 5
y = 5
[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }
size = 10
[colors]
primary = { foreground = "#c0caf5", background = "#24283b" }
cursor = { text = "#24283b", cursor = "#c0caf5" }
selection = { text = "#c0caf5", background = "#2e3c64" }
normal = { black = "#1d202f", red = "#f7768e", green = "#9ece6a", yellow = "#e0af68", blue = "#7aa2f7", magenta = "#bb9af7", cyan = "#7dcfff", white = "#a9b1d6" }
bright = { black = "#414868", red = "#f7768e", green = "#9ece6a", yellow = "#e0af68", blue = "#7aa2f7", magenta = "#bb9af7", cyan = "#7dcfff", white = "#c0caf5" }
[cursor]
style = { shape = "Block", blinking = "On" }
